Building With Responsive Design : TNW-Website-Clone
DeliceLydia/TNW-Website-Clone pull request #1
Opened 2020-09-13 18:01 UTC by DeliceLydia

This project consists of replicating The Next Web website putting emphasis on how it behaves differently depending on the size of the screen where the website is rendered.

- Setup project dependencies like GitHub Actions and Linters via Microverse Linters Config.

- Used a mobile-first approach when dealing with media queries with 2 breakpoints

- Aligned all elements with float and flex or grid.

2020-09-13 18:03 UTC, DeliceLydia commented
> Try to use shorter commit messages.
> 
> You can include a description where necessary.

noted

2020-09-13 21:49 UTC, SafaErden requested changes
## Status: Require changes ♻️

**Hi @DeliceLydia, your project is awesome. 👐 However, we need a little fix before we can proceed. Kindly find the comments below**
##

**REQUIRED CHANGES**

- [ ] The Latest Funding section is missing. Please add it as it appears on the original page.

- [ ] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

* You repeat some of the CSS rules several times in your stylesheet. Please apply DRY CSS rules.

- [ ] The other requested changes are listed below. Please kindly fix them.

##

**NOTES**

Please use the imperative tense for all your commit messages in your upcoming projects.

##

**SUMMARY**

As I mentioned above, your project is almost done. You have some minor issues to solve. Please be an optimist and do not forget that the main purpose is to learn and practice. Do not let the requested changes discourage you 👍

##

*Kindly make the changes and submit another code review when you are ready*

Questions or comments? Reach me on [Twitter](https://twitter.com/safaerden) or [LinkedIn](https://www.linkedin.com/in/safaerden/) 🗨️

Happy coding_ 👨‍💻 

**Safa ERDEN**

2020-09-13 21:49 UTC, SafaErden commented on index.html
> +          </ul>
- [ ] The page contains a search icon at the rightmost side of the sub-navigation row in the original large screen but the search icon is missing in your version. Please add it.

- [ ] Also the navigation and the sub-navigation items should be aligned left but in your version, there is a redundant empty space, please fix your CSS rules to create the same UI with the original page.

![image](https://user-images.githubusercontent.com/60184961/93028723-5690bf80-f61e-11ea-83c4-e8a41fc15cf1.png)

2020-09-13 21:49 UTC, SafaErden commented on index.html
> +      </div>
- [ ] In medium view the TWN logo appears at the leftmost part but the navigation menu overlaps it and there is a redundant empty space on the right side of the navigation menu. Please kindly fix it.

![image](https://user-images.githubusercontent.com/60184961/93028789-e171ba00-f61e-11ea-8820-4788d1f5479a.png)

2020-09-13 21:49 UTC, SafaErden commented on index.html
> +    <nav class="nav">
- [ ] In the original page in the small screen, the Navigation and sub-navigation row changes to a hamburger (bars) icon at the rightmost part (next to seach icon), but in your version, the search icon is missing and the hamburger bars are not aligned right. Please fix these issues.

![image](https://user-images.githubusercontent.com/60184961/93028827-301f5400-f61f-11ea-82f5-87e1d01b815f.png)

2020-09-13 21:49 UTC, SafaErden commented on index.html
> +          <div>
- [ ] The second article's title is missing, please add it.

![image](https://user-images.githubusercontent.com/60184961/93028958-3f52d180-f620-11ea-933d-1a7b0a849a4c.png)

2020-09-13 21:49 UTC, SafaErden commented on index.html
> +        </div>
- [ ] The top 3 articles section in large screens should contain the TWN logo at the top left corner of the row ([link to page](https://thenextweb.com/)). But the logo is missing in your version. Please kindly add it.

![image](https://user-images.githubusercontent.com/60184961/93028899-c2bff300-f61f-11ea-87c5-a7e120dd26bc.png)

2020-09-13 21:49 UTC, SafaErden commented on index.html
> +          <div class="inside">
- [ ] Please add some space between the articles for the small screen view.

![image](https://user-images.githubusercontent.com/60184961/93028982-75905100-f620-11ea-9974-9736b24a1dba.png)

2020-09-13 21:49 UTC, SafaErden commented on index.html
> +      <h2 class="latest-heading">Latest news</h2>
- [ ] There is an empty space on the right side of the latest news section in the medium screen view. Please fix it to create the same UI with the original page.

![image](https://user-images.githubusercontent.com/60184961/93029024-da4bab80-f620-11ea-9076-872c381923b5.png)

2020-09-13 21:49 UTC, SafaErden commented on index.html
> +        <h2 class="section-h2">HARD FORK</h2>
- [ ] This title shouldn't be all letters capitalized. 

![image](https://user-images.githubusercontent.com/60184961/93029096-5c3bd480-f621-11ea-9b56-50ce00464b7f.png)

2020-09-13 21:49 UTC, SafaErden commented on index.html
> +    <div class="flex">
- [ ] There is a redundant empty space on the right side of your page in the medium screen view. Please fix your content to fill the full width independent from the screen size.

![image](https://user-images.githubusercontent.com/60184961/93029122-8e4d3680-f621-11ea-95a4-f242c3c69f7f.png)

2020-09-13 21:49 UTC, SafaErden commented on index.html
> +      <div class="flex-container">
- [ ] This section should have 3 category boxes per row in large screens, but in your version, there are 4 boxes. Please kindly fix it.

![image](https://user-images.githubusercontent.com/60184961/93029164-ef750a00-f621-11ea-97c0-d2312605eb9f.png)

2020-09-13 21:49 UTC, SafaErden commented on index.html
> +    <div class="hard-fork flex-container">
- [ ] There is a redundant empty space in the medium screen view on the right side. Please fix your content to fill the full width independent from the screen size.

![image](https://user-images.githubusercontent.com/60184961/93029241-67dbcb00-f622-11ea-8dc3-9ee5813c9c1e.png)

2020-09-13 21:49 UTC, SafaErden commented on index.html
> +    </div>
- [ ] The footer contains TNW logo with a copyright paragraph ([link to page](https://thenextweb.com/)). But the logo is missing in your version. Please add it.

![image](https://user-images.githubusercontent.com/60184961/93029307-cb65f880-f622-11ea-804d-44391d01490d.png)

2020-09-13 21:49 UTC, SafaErden commented on css/style.css
> +@media (min-width: 320px) {
- [ ] No small breakpoint as it is mobile-first and the base styles are for the mobile screen. ([Screenshot on mobile-first approach](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/mobile_first.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/))

* medium: min-width around 768px
* large: min-width 1024px

2020-09-13 21:49 UTC, SafaErden commented on css/style.css
> +/* template */
- [ ] Please remove unnecessary comments.

2020-09-13 21:49 UTC, SafaErden commented on index.html
> +  <header>
- [ ] Instead of wrapping the `nav `tag with `header `tag, you should wrap your `header `tag with the `nav `tag.

2020-09-14 18:09 UTC, teekaytech requested changes
# Changes Required :point_down:

**Hi @DeliceLydia, you have done an amazing job so far :muscle:. But there's a saying which says *it is not over until it is over*. Let's quickly make the changes below before we proceed**. 

* * *

**[ REQUIRED ]**

- [ ] The latest funding section aligns 4 articles per row ([link to page](https://thenextweb.com/)) for large screens
- [ ] The latest funding section aligns 1 articles per row ([link to page](https://thenextweb.com/)) for medium screen version
- [ ] In the latest news section, the large screen size version is having more empty space to the right. Please find a way to justify this space between the left and right margins.
- [ ] I pointed out some other required changes below. Please go through them and fix them as appropriate.

Comments:
- Try to be consistent in the way you use units (px, em, %, etc) for your CSS rules. Read more about CSS units and values from this [MDN page](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units)
* * *
**In Summary**
We all know that this project is a big one with massive content. Try to observe closely the main website. Everything I pointed out is well placed in there. You are almost there, kindly make the changes carefully and submit another request form as soon as you are done.

**I'm available on github (@teekaytech) and slack (@taofeekolalere)

2020-09-14 18:09 UTC, teekaytech commented on index.html
> +          </ul>
I can see that you've included the search icon, but it's only showing on small screen size. The requirement says you should implement the search icon for a large screen size. Rendering the icon on small screen size is okay, but not required.

**Large version**
- [x] It contains search icon at the rightmost side of sub-navigation row ([link to page](https://thenextweb.com/))

2020-09-14 18:09 UTC, teekaytech commented on index.html
> +            <span class="small-text">by Bryan Clark</span>
The last TSE mentioned that you should place the TWN logo at the top left corner of the row. Kindly look at the [main page](https://thenextweb.com/) and add the logo to your version, for medium screen. The box is present, but the TNW wording is missing.

**Medium version changes**
- [x]  TWN logo appears at the leftmost part ([link to page](https://thenextweb.com/))

2020-09-14 18:09 UTC, teekaytech commented on css/style.css
> +/*
These comments are not necessary. Kindly remove them.

2020-09-15 09:22 UTC, arslanbisharat commented
### Congratulations APPROVED :clap:
Hello Team! I can see you worked really hard on this project. I reviewed your [project](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/)  and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
Now you can merge the branches and move forward with your curriculum. 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 
**Happy Coding**:smiley:
-------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) @slack: arslanbisharat

2020-09-15 09:23 UTC, arslanbisharat approved these changes
### Congratulations APPROVED :clap:
Hello Team! I can see you worked really hard on this project. I reviewed your [project](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/)  and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
Now you can merge the branches and move forward with your curriculum. 

[OPTIONAL] Make your footer exactly the same as the given website by adding width 
[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 
**Happy Coding**:smiley:
-------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) @slack: arslanbisharat

2020-09-15 09:29 UTC, merged